### ISSUE TITLE
Define the tasks/subtasks for Gluster CSI driver.

### ISSUE THREAD

**Issue by humblec** [gluster/gluster-csi-driver#6]
As CSI driver has to communicate various other components, its good to define the tasks or requirements which has to be met by the CSI driver. @JohnStrunk can we start filing issues for the same ?

**Comment by JohnStrunk** [comment]
Sure.
Off the top of my head, we need issues for:
- [ ] CI testing
- [ ] Documentation of driver design & dependencies on external components
- [ ] Design for the flow of each CSI request type
- [ ] Design of StorageClass parameters

**Comment by JohnStrunk** [comment]
- CI is #41 & #9
- StorageClass is #30
